# Generated by Django 3.2 on 2023-01-06 01:25

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='country',
            field=django_countries.fields.CountryField(default=2, max_length=2),
            preserve_default=False,
        ),
    ]
